apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-deployment
spec:
  selector:
    matchLabels:
      app: dotnet
  template:
    metadata:
      labels:
        app: dotnet
    spec:
      containers:
        - name: dotnet
          image: dotnet:v2
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          env:
            - name: MongoDbSettings__Host
              value: mongodb-service
            - name: MongoDbSettings__Db
              value: dotnet
            - name: MongodbSettings__Password
              valueFrom:
                secretKeyRef:
                  name: dotnet-secrets
                  key: mongodb-password
          livenessProbe:
            httpGet:
              path: /health/live
              port: 80
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-service
spec:
  type: LoadBalancer
  selector:
    app: dotnet
  ports:
    - port: 80
      targetPort: 80

